import { Inter } from 'next/font/google'
import './globals.css'
import HeaderNav from '@/components/ui/headerNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alchmotion Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <HeaderNav />

        {children}
      </body>
    </html>
  )
}
